/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.List;
 
public class ZippyTest {

    @Test
    void zipTwoIntegerLists() {
        List<Integer> list1 = List.of(1, 3, 5);
        List<Integer> list2 = List.of(2, 4, 6);

        List<Integer> expected = List.of(1, 2, 3, 4, 5, 6);
        assertEquals(expected, Zippy.zip(list1, list2));
    }

    @Test
    void zipStringsUnequalLength() {
        List<String> list1 = List.of("A", "B", "C");
        List<String> list2 = List.of("X", "Y");

        List<String> expected = List.of("A", "X", "B", "Y", "C");
        assertEquals(expected, Zippy.zip(list1, list2));
    }

    @Test
    void zipFirstListEmpty() {
        List<String> list1 = List.of();
        List<String> list2 = List.of("A", "B");

        List<String> expected = List.of("A", "B");
        assertEquals(expected, Zippy.zip(list1, list2));
    }

    @Test
    void zipBothListsEmpty() {
        List<Object> list1 = List.of();
        List<Object> list2 = List.of();

        List<Object> expected = List.of();
        assertEquals(expected, Zippy.zip(list1, list2));
    }
}